version: "3.9"

services:
  database:
    image: postgres
    container_name: database_servicoDeAgendamento
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ferraz
      - POSTGRES_DB=servicoDeAgendamento
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: servicoDeAgendamento
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
